---
apiVersion: v1
kind: Namespace
metadata:
  name: wekan
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: wekan
  namespace: wekan
spec:
  interval: 24h
  url: https://wekan.github.io/charts

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wekan
  namespace: wekan
spec:
  interval: 30m
  chart:
    spec:
      chart: wekan
      version: "1.2.x"
      sourceRef:
        kind: HelmRepository
        name: wekan
        namespace: wekan
      interval: 12h
  values:
    endpoint: wekan.snowflake.cash
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
        external-dns.alpha.kubernetes.io/hostname: wekan.snowflake.cash.

      hosts:
        - wekan.snowflake.cash
      tls:
        - hosts:
            - wekan.snowflake.cash
          secretName: wekan-iteam-pub-tls
    mongodb:
      replicaCount: 1
      mailUrl: "smtp://smtp-relay.gmail.com:587"