---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: happylou
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/upphandling/landing-page.git

