apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: happylou
  namespace: flux-system
spec:
  interval: 30s
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: happylou
  targetNamespace: happylou