apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-values
  namespace: postgresql
data:
  values.yaml: |-
            
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  chart:
    spec:
      chart: postgresql
      version: 12.1.15
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  interval: 15m
  timeout: 5m
  releaseName: postgresql
  valuesFrom:
  - kind: ConfigMap
    name: postgresql-values
    valuesKey: values.yaml