---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: iteam-next-site
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: feat/k8s
  url: https://github.com/iteam1337/iteam-next-site

