apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

helmCharts:
- name: redis
  releaseName: redis
  namespace: redis
  version: 15.0.1
  repo: https://charts.bitnami.com/bitnami