apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test

spec:
  containers:
  - name: test
    image: busybox
    command: ["sleep", "3600"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always