apiVersion: v1
kind: Namespace
metadata:
  name: test
---
apiVersion: v1
kind: Pod
metadata:
  namespace: test
  name: test
  labels:
    name: test
spec:
  containers:
  - name: test
    image: busybox
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
