---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: mandatkollen
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/iteam1337/mandatkollen

